# Generated by Django 4.1.4 on 2023-10-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0012_alter_employeeregister_details_emp_profile'),
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontaken',
            name='act_emp_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_emp_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='emp_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='emp_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_emp_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='emp_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details'),
        ),
    ]
