# Generated by Django 4.1.4 on 2023-10-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0013_departmentregister_details_dept_content_and_more'),
        ('DM_Head', '0004_employeeleave_no_of_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_status', models.IntegerField(default=0)),
                ('alloaction_date', models.DateField(null=True)),
                ('allocatEmp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('allocat_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeRegister', to='Registration_Login.employeeregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='Previos_Allocation_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_from_date', models.DateField(null=True)),
                ('previous_to_date', models.DateField(null=True)),
                ('previousemp_id', models.IntegerField(default=0)),
                ('previousemp_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('previousemp_allocatedTo', models.IntegerField(default=0)),
                ('previousemp_allocatedName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('allocate_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.allocation_details')),
                ('newallocation_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
            ],
        ),
    ]
