# Generated by Django 4.2.5 on 2023-10-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logregister_details',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BusinessRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owner_lname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('company_image', models.FileField(default='', upload_to='profiles')),
                ('company_website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('company_active_status', models.IntegerField(default=0)),
                ('log_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details')),
            ],
        ),
    ]
