# Generated by Django 4.2.5 on 2023-10-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0002_logregister_details_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregister_details',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DepartmentRegister_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dept_active_status', models.IntegerField(default=0)),
                ('dept_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('brd_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
            ],
        ),
    ]
