# Generated by Django 4.2.5 on 2023-10-05 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0003_businessregister_details_reg_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationRegister_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('desig_active_status', models.IntegerField(default=0)),
                ('desig_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('dept_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.departmentregister_details')),
                ('desig_brd_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
            ],
        ),
    ]
