# Generated by Django 4.2.5 on 2023-10-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0004_designationregister_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('emp_profife', models.FileField(default='', upload_to='profiles')),
                ('emp_file', models.FileField(default='', upload_to='employee_files')),
                ('emp_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emp_pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('emp_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('emp_district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('emp_state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('emp_active_status', models.IntegerField(default=0)),
                ('emp_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('emp_comp_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
                ('emp_department_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.departmentregister_details')),
                ('emp_designation_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.designationregister_details')),
                ('logreg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details')),
            ],
        ),
    ]
