# Generated by Django 4.2.5 on 2023-10-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0005_employee_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Details',
            new_name='EmployeeRegister_Details',
        ),
    ]
