# Generated by Django 4.2.5 on 2023-10-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0006_rename_employee_details_employeeregister_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorRegister_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_contact_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('dis_profife', models.FileField(default='', upload_to='profiles')),
                ('dis_file', models.FileField(default='', upload_to='employee_files')),
                ('dis_address1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_address3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dis_pin', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('dis_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('dis_district', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('dis_state', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('dis_active_status', models.IntegerField(default=0)),
                ('dis_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('logdis_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.logregister_details')),
            ],
        ),
    ]
