# Generated by Django 4.2.5 on 2023-10-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0008_distributorregister_details_dis_agencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregister_details',
            name='distributor_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.distributorregister_details'),
        ),
    ]
