# Generated by Django 4.2.5 on 2023-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0009_businessregister_details_distributor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister_details',
            name='emp_verify_status',
            field=models.IntegerField(default=0),
        ),
    ]
