# Generated by Django 4.1.4 on 2023-10-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0012_alter_employeeregister_details_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentregister_details',
            name='dept_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='designationregister_details',
            name='desig_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
